# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gigardin <gigardin@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/12/09 20:31:45 by gigardin          #+#    #+#              #
#    Updated: 2023/12/09 20:32:20 by gigardin         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = cc
CFLAGS = -Wall -Wextra -Werror
RM = rm -rf

LIBFT = ./libft/libft.a

CLIENT = client
SERVER = server

SRC_C = src/client.c
OBJ_C = $(SRC_C:%.c=%.o)

SRC_S = src/server.c
OBJ_S = $(SRC_S:%.c=%.o)
